import { Clinic, Doctor, Stats } from '../types';

export const MOCK_CLINICS: Clinic[] = [
  {
    id: '1',
    name: "1-sonli Shahar Ko'p Tarmoqli Klinikasi",
    shortName: '1-SMK',
    address: "Mirzo Ulug'bek tumani, Mustaqillik ko'chasi 45",
    district: "Mirzo Ulug'bek",
    lat: 41.3375, lng: 69.3438,
    phone: '+998 71 267-01-01',
    workHours: '08:00 – 18:00',
    workDays: 'Dushanba – Shanba',
    totalDoctors: 24,
    rating: 4.5,
    specializations: ['Terapevt', 'Kardiolog', 'Nevrolog', 'Jarroh', 'Pediatr'],
    isOpen: true,
  },
  {
    id: '2',
    name: 'Ibn Sino Nomidagi Respublika Ixtisoslashtirilgan Klinikasi',
    shortName: 'Ibn Sino RMDK',
    address: 'Yakkasaroy tumani, Farob ko\'chasi 1',
    district: 'Yakkasaroy',
    lat: 41.295, lng: 69.2405,
    phone: '+998 71 233-22-40',
    workHours: '08:00 – 17:00',
    workDays: 'Dushanba – Juma',
    totalDoctors: 38,
    rating: 4.8,
    specializations: ['Kardiolog', 'Onkolog', 'Jarroh', 'Endokrinolog'],
    isOpen: true,
  },
  {
    id: '3',
    name: 'Yunusobod Tumani Markaziy Poliklinikasi',
    shortName: 'Yunusobod MTP',
    address: 'Yunusobod tumani, Amir Temur shoh ko\'chasi 108',
    district: 'Yunusobod',
    lat: 41.363, lng: 69.298,
    phone: '+998 71 264-00-10',
    workHours: '08:00 – 18:00',
    workDays: 'Dushanba – Shanba',
    totalDoctors: 19,
    rating: 4.2,
    specializations: ['Terapevt', 'Pediatr', 'Ginekolog', 'Oftalmolog'],
    isOpen: true,
  },
  {
    id: '4',
    name: 'Chilonzor Tumani 15-Son Poliklinikasi',
    shortName: 'Chilonzor 15-son',
    address: 'Chilonzor tumani, Bunyodkor ko\'chasi 3',
    district: 'Chilonzor',
    lat: 41.298, lng: 69.195,
    phone: '+998 71 277-50-00',
    workHours: '08:00 – 17:00',
    workDays: 'Dushanba – Shanba',
    totalDoctors: 16,
    rating: 4.0,
    specializations: ['Terapevt', 'Nevrolog', 'Ortoped', 'Stomatolog'],
    isOpen: false,
  },
  {
    id: '5',
    name: 'Sergeli Tumani Markaziy Poliklinikasi',
    shortName: 'Sergeli MTP',
    address: 'Sergeli tumani, Yangi Sergeli ko\'chasi 22',
    district: 'Sergeli',
    lat: 41.225, lng: 69.24,
    phone: '+998 71 259-10-10',
    workHours: '08:00 – 18:00',
    workDays: 'Dushanba – Shanba',
    totalDoctors: 21,
    rating: 4.3,
    specializations: ['Terapevt', 'Pediatr', 'Jarroh', 'Kardiolog'],
    isOpen: true,
  },
  {
    id: '6',
    name: "Shayxontohur Tumani Ko'p Tarmoqli Klinikasi",
    shortName: 'Shayxontohur MTK',
    address: "Shayxontohur tumani, Ko'kcha ko'chasi 17",
    district: 'Shayxontohur',
    lat: 41.326, lng: 69.234,
    phone: '+998 71 244-33-55',
    workHours: '08:00 – 17:00',
    workDays: 'Dushanba – Shanba',
    totalDoctors: 18,
    rating: 4.1,
    specializations: ['Terapevt', 'Endokrinolog', 'Ginekolog', 'Pediatr'],
    isOpen: true,
  },
];

export const MOCK_DOCTORS: Doctor[] = [
  // Clinic 1
  { id: 'd1', clinicId: '1', name: 'Akmal Karimov', specialization: 'Jarroh', experience: 12, photo: null, queue: 10, avgTime: 15 },
  { id: 'd2', clinicId: '1', name: 'Maftuna Toshmatova', specialization: 'Terapevt', experience: 8, photo: null, queue: 7, avgTime: 12 },
  { id: 'd3', clinicId: '1', name: 'Bobur Yusupov', specialization: 'Kardiolog', experience: 15, photo: null, queue: 5, avgTime: 20 },
  { id: 'd4', clinicId: '1', name: 'Nilufar Rahimova', specialization: 'Nevrolog', experience: 10, photo: null, queue: 8, avgTime: 18 },
  { id: 'd5', clinicId: '1', name: 'Sanjar Mirzayev', specialization: 'Pediatr', experience: 6, photo: null, queue: 12, avgTime: 10 },
  // Clinic 2
  { id: 'd6', clinicId: '2', name: 'Dilshod Xolmatov', specialization: 'Kardiolog', experience: 20, photo: null, queue: 14, avgTime: 25 },
  { id: 'd7', clinicId: '2', name: 'Zulfiya Nazarova', specialization: 'Onkolog', experience: 18, photo: null, queue: 6, avgTime: 30 },
  { id: 'd8', clinicId: '2', name: 'Rustam Abdullayev', specialization: 'Jarroh', experience: 22, photo: null, queue: 9, avgTime: 20 },
  { id: 'd9', clinicId: '2', name: 'Gavhar Ismoilova', specialization: 'Endokrinolog', experience: 14, photo: null, queue: 11, avgTime: 22 },
  // Clinic 3
  { id: 'd10', clinicId: '3', name: 'Umid Rashidov', specialization: 'Terapevt', experience: 7, photo: null, queue: 5, avgTime: 12 },
  { id: 'd11', clinicId: '3', name: 'Shahlo Ergasheva', specialization: 'Pediatr', experience: 9, photo: null, queue: 13, avgTime: 10 },
  { id: 'd12', clinicId: '3', name: 'Jasur Normatov', specialization: 'Ginekolog', experience: 11, photo: null, queue: 7, avgTime: 20 },
  { id: 'd13', clinicId: '3', name: 'Kamola Xasanova', specialization: 'Oftalmolog', experience: 8, photo: null, queue: 4, avgTime: 15 },
  // Clinic 4
  { id: 'd14', clinicId: '4', name: 'Behruz Qodirov', specialization: 'Terapevt', experience: 5, photo: null, queue: 3, avgTime: 12 },
  { id: 'd15', clinicId: '4', name: 'Mohira Sultonova', specialization: 'Nevrolog', experience: 13, photo: null, queue: 8, avgTime: 18 },
  { id: 'd16', clinicId: '4', name: 'Eldor Xoliqov', specialization: 'Ortoped', experience: 16, photo: null, queue: 6, avgTime: 25 },
  // Clinic 5
  { id: 'd17', clinicId: '5', name: 'Feruz Tursunov', specialization: 'Terapevt', experience: 9, photo: null, queue: 9, avgTime: 12 },
  { id: 'd18', clinicId: '5', name: 'Dilorom Yunusova', specialization: 'Pediatr', experience: 12, photo: null, queue: 15, avgTime: 10 },
  { id: 'd19', clinicId: '5', name: 'Alisher Nishonov', specialization: 'Jarroh', experience: 17, photo: null, queue: 5, avgTime: 20 },
  // Clinic 6
  { id: 'd20', clinicId: '6', name: 'Muazzam Xoliqova', specialization: 'Terapevt', experience: 11, photo: null, queue: 7, avgTime: 12 },
  { id: 'd21', clinicId: '6', name: 'Otabek Pulatov', specialization: 'Endokrinolog', experience: 14, photo: null, queue: 10, avgTime: 20 },
  { id: 'd22', clinicId: '6', name: 'Nargiza Sotvoldiyeva', specialization: 'Ginekolog', experience: 8, photo: null, queue: 6, avgTime: 18 },
];

export const MOCK_STATS: Stats = {
  totalClinics: 6,
  openClinics: 5,
  totalDoctors: 22,
  activeDoctors: 18,
  currentQueue: MOCK_DOCTORS.reduce((s, d) => s + d.queue, 0),
  todayServed: 247,
};
